config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/null-break/argocd-example-apps
      targetRevision: master

applications:
  - name: helm-sample-1
    namespace: argo-cd
    tool:
      helm:
        releaseName: helm-sample-1
        valuesObject:
          replicaCount: 3
  - name: helm-sample-3
    namespace: argo-cd
    tool:
      helm:
        releaseName: helm-sample-3
