config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/null-break/argocd-example-apps
      targetRevision: master

applications:
  - name: guestbook
  - name: guestbook-2
